// ⚠️  This file is auto-generated by FlutterFire CLI.
// Run the following command to generate it for your Firebase project:
//
//   dart pub global activate flutterfire_cli
//   flutterfire configure
//
// After running, this file will be replaced with your actual Firebase config.
// Until then, the app will not connect to Firebase.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) throw UnsupportedError('Web not configured');
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError('Platform not configured');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZIxXdzqoxjj7u1CoDG86-Gfrn3XPNTsg',
    appId: '1:1025717374734:android:e65d2865ad57eabb06115f',
    messagingSenderId: '1025717374734',
    projectId: 'smart-security-camera-40d2b',
    storageBucket: 'smart-security-camera-40d2b.firebasestorage.app',
  );

  // ── Replace these values after running `flutterfire configure` ──

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUftbbCoGxokunEvf2qeKKir4MkCtgGn4',
    appId: '1:1025717374734:ios:ef2c6a9de5e0a5eb06115f',
    messagingSenderId: '1025717374734',
    projectId: 'smart-security-camera-40d2b',
    storageBucket: 'smart-security-camera-40d2b.firebasestorage.app',
    iosBundleId: 'com.example.smartSecurityCamera',
  );

}