// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBInP2tWX1aoto3jfuJ5LRC4ma-pn6zwRg',
    appId: '1:1025717374734:web:fac193eb7c8c4a7d06115f',
    messagingSenderId: '1025717374734',
    projectId: 'smart-security-camera-40d2b',
    authDomain: 'smart-security-camera-40d2b.firebaseapp.com',
    storageBucket: 'smart-security-camera-40d2b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZIxXdzqoxjj7u1CoDG86-Gfrn3XPNTsg',
    appId: '1:1025717374734:android:e65d2865ad57eabb06115f',
    messagingSenderId: '1025717374734',
    projectId: 'smart-security-camera-40d2b',
    storageBucket: 'smart-security-camera-40d2b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUftbbCoGxokunEvf2qeKKir4MkCtgGn4',
    appId: '1:1025717374734:ios:ef2c6a9de5e0a5eb06115f',
    messagingSenderId: '1025717374734',
    projectId: 'smart-security-camera-40d2b',
    storageBucket: 'smart-security-camera-40d2b.firebasestorage.app',
    iosBundleId: 'com.example.smartSecurityCamera',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUftbbCoGxokunEvf2qeKKir4MkCtgGn4',
    appId: '1:1025717374734:ios:ef2c6a9de5e0a5eb06115f',
    messagingSenderId: '1025717374734',
    projectId: 'smart-security-camera-40d2b',
    storageBucket: 'smart-security-camera-40d2b.firebasestorage.app',
    iosBundleId: 'com.example.smartSecurityCamera',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBInP2tWX1aoto3jfuJ5LRC4ma-pn6zwRg',
    appId: '1:1025717374734:web:1072db9a3249c8de06115f',
    messagingSenderId: '1025717374734',
    projectId: 'smart-security-camera-40d2b',
    authDomain: 'smart-security-camera-40d2b.firebaseapp.com',
    storageBucket: 'smart-security-camera-40d2b.firebasestorage.app',
  );
}
